[graph]
all-features = true

[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]
yanked = "warn"
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "MIT",
  "Unlicense",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
deny = []
skip = [{ name = "windows-sys" }]
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
